server:
  port: 7070

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abdul8377/DAD-2024-2.git # ruta del repositorio git
          searchPaths: config-data
          default-label: evaluacion_Unidad2
  security:
    user:
      name: root
      password: 123456
