server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true

      routes:
        - id: ms-catalogo-service, ms-product-service
          uri: lb://ms-catalogo-service, lb://ms-product-service
          predicates:
            - Path=/Category/**, Path=/Product/**
